# Generated by Django 4.1 on 2025-01-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='department name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='gender')),
                ('salary', models.CharField(max_length=32, verbose_name='salary')),
                ('create_time', models.DateField(verbose_name='employed date')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.department')),
            ],
        ),
    ]
