# Generated by Django 4.1 on 2025-01-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="departure",
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_one.department",
            ),
        ),
    ]
