# Generated by Django 4.1 on 2025-01-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0003_alter_employee_department_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_one.employee",
                verbose_name="user_name",
            ),
        ),
    ]
