# Generated by Django 4.1 on 2025-01-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0004_alter_assets_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assets",
            old_name="times",
            new_name="create_time",
        ),
    ]
