# Generated by Django 4.1 on 2025-01-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0006_alter_assets_phone_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=32, verbose_name="uver_name"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="password")),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "Visitor"), (1, "User"), (2, "Root")],
                        verbose_name="role",
                    ),
                ),
            ],
        ),
    ]
