# Generated by Django 4.1 on 2025-01-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0007_userrole"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRole",
            new_name="Permission",
        ),
    ]
