# Generated by Django 4.1 on 2025-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0008_rename_userrole_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="user_name",
            field=models.CharField(max_length=32, verbose_name="user_name"),
        ),
    ]
